name: Comment ESLint Results

on:
  workflow_run:
    workflows: ["Run ESLint"]
    types:
      - completed

jobs:
  comment-lint-results:
    if: github.event.workflow_run.conclusion == 'failure'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Download Lint Results
        id: download
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |

            try {
              core.info('Downloading lint-results artifact');

              // Grab the run ID from the payload
              const runId = context.payload.workflow_run.id;

              const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: runId
              });

              const art = artifacts.data.artifacts.find(a => a.name === "lint-results");
              if (!art) {
                core.setFailed('No lint-results artifact found');
                return 'false';
              }

              core.info(`Found artifact id ${art.id}, downloading…`);
              const dl = await github.rest.actions.downloadArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: art.id,
                archive_format: 'zip'
              });

              require('fs').writeFileSync('lint-results.zip', Buffer.from(dl.data));
              core.info('Downloaded and saved lint-results.zip');
              return 'true';

            } catch (err) {
              core.setFailed(`Download failed: ${err.message}`);
              return 'false';
            }

      - name: Extract Lint Results
        if: steps.download.outputs.result == 'true'
        id: extract
        run: |
          mkdir -p lint-results
          unzip -o lint-results.zip -d lint-results

          if [ -f lint-results/errors.md ]; then
            echo "LINT_ERRORS<<EOF" >> $GITHUB_ENV
            cat lint-results/errors.md >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
            echo "HAS_ERRORS=true" >> $GITHUB_OUTPUT
          else
            echo "HAS_ERRORS=false" >> $GITHUB_OUTPUT
          fi

      - name: Post Lint Results as PR Comment
        if: steps.extract.outputs.HAS_ERRORS == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            try {
              // core and github injected by actions/github-script
              const pulls = context.payload.workflow_run.pull_requests;
              core.info(`Found ${pulls.length} triggering PR(s)`);

              if (pulls.length === 0) {
                core.warning('No associated PRs; skipping comment.');
                return;
              }

              const body = process.env.LINT_ERRORS;
              for (const pr of pulls) {
                core.info(`Commenting lint errors on PR #${pr.number}`);
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo:  context.repo.repo,
                  issue_number: pr.number,
                  body
                });
              }
              core.info('All comments posted');
            } catch (err) {
              core.error('Failed to post lint comment:', err);
              core.setFailed(err.message);
            }
