name: Tests

on:
  push:
    branches:
      - master

jobs:
  coverage:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.16.0

    - name: Install Dependencies
      run: npm install

    - name: Run Tests with Coverage
      run: npm run test

    - name: Generate Coverage Report
      run: npx c8 report --reporter=lcov

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: blits-coverage
        fail_ci_if_error: false
