name: Run Blits Tests

on:
  pull_request:
    branches:
      - dev
      - master

jobs:
  run-blits-tests:
    runs-on: ubuntu-latest
    outputs:
      tests_failed: ${{ steps.set-result.outputs.tests_failed }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.16.0

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      id: run-tests
      run: |
        # Run tests and capture exit code
        if ! npm run test > test-report.txt 2>&1; then
          echo "tests_failed=true" >> $GITHUB_OUTPUT
          echo "exit_code=$?" >> $GITHUB_OUTPUT
        fi

    - name: Get Current Timestamp
      id: timestamp
      run: echo "timestamp=$(date)" >> $GITHUB_OUTPUT

    - name: Extract Test Summary
      id: test-summary
      run: |
        # Check if test-report.txt exists and has content
        if [ -s test-report.txt ]; then
          # Check if we already know tests failed from exit code
          if [[ "${{ steps.run-tests.outputs.tests_failed }}" == "true" ]]; then
            echo "summary=Test execution failed" >> $GITHUB_OUTPUT
            echo "tests_failed=true" >> $GITHUB_OUTPUT
            # Capture the error output for the comment
            echo "error<<EOF" >> $GITHUB_OUTPUT
            cat test-report.txt >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Check for a situation where we have errors but the test runner still completed with 0 tests
          if grep -q "Error" test-report.txt && grep -q "of 0 tests" test-report.txt; then
            echo "summary=Test execution encountered errors. No tests were run." >> $GITHUB_OUTPUT
            echo "tests_failed=true" >> $GITHUB_OUTPUT
            # Capture the error output for the comment
            echo "error<<EOF" >> $GITHUB_OUTPUT
            cat test-report.txt >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Search for a line containing both "passed:" and "failed:"
          summary=$(grep -E "passed:.*failed:" test-report.txt | head -n1)

          if [ -n "$summary" ]; then
            # Extract test numbers for clearer reporting
            echo "summary=$summary" >> $GITHUB_OUTPUT

            # Extract the number of failed tests
            failed=$(echo "$summary" | sed -E 's/.*failed:\s*([0-9]+).*/\1/')
            # Extract the total number of tests
            total=$(echo "$summary" | sed -E 's/.*of\s*([0-9]+)\s*tests.*/\1/')

            # Mark as failed if there are failed tests OR if 0 tests were found
            if [ "$failed" -gt 0 ]; then
              echo "tests_failed=true" >> $GITHUB_OUTPUT
            elif [ "$total" -eq 0 ]; then
              echo "tests_failed=true" >> $GITHUB_OUTPUT
              echo "summary=No tests were found to run. This is considered a failure." >> $GITHUB_OUTPUT
            fi
          else
            echo "summary=Test execution produced no valid test summary" >> $GITHUB_OUTPUT
            echo "tests_failed=true" >> $GITHUB_OUTPUT
            # Capture the error output for the comment
            echo "error<<EOF" >> $GITHUB_OUTPUT
            cat test-report.txt >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi
        else
          echo "summary=Test execution error: No test output generated." >> $GITHUB_OUTPUT
          echo "tests_failed=true" >> $GITHUB_OUTPUT
        fi

    - name: Set Result
      id: set-result
      run: |
        if [[ "${{ steps.run-tests.outputs.tests_failed }}" == "true" || "${{ steps.test-summary.outputs.tests_failed }}" == "true" ]]; then
          echo "tests_failed=true" >> $GITHUB_OUTPUT
        else
          echo "tests_failed=false" >> $GITHUB_OUTPUT
        fi

    - name: Upload Test Report Artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: test-report.txt

    # Create a file with test results to be used by the comment workflow
    - name: Save Test Results
      if: always()
      run: |
        mkdir -p ./test-results
        echo "${{ steps.timestamp.outputs.timestamp }}" > ./test-results/timestamp.txt
        echo "${{ steps.test-summary.outputs.summary != '' && steps.test-summary.outputs.summary || 'Test execution failed' }}" > ./test-results/summary.txt
        echo "${{ steps.set-result.outputs.tests_failed }}" > ./test-results/failed.txt

        # Save error output if it exists
        if [ -n "${{ steps.test-summary.outputs.error }}" ]; then
          echo "${{ steps.test-summary.outputs.error }}" > ./test-results/error.txt
        fi

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ./test-results/

    # Fail the workflow if tests failed
    - name: Check Test Status
      if: steps.set-result.outputs.tests_failed == 'true'
      run: exit 1
